version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 10
  receiver1:
    build: ./receiver
    container_name: 'receiver1'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment: 
      - TOPIC=iman
  receiver2:
    build: ./receiver
    container_name: 'receiver2'
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment: 
      - TOPIC=iman
  sender:
    build: ./sender
    container_name: 'sender'
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '3000:3000'
