version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  app:
    restart: always
    build: ./
    depends_on:
      - rabbitmq
    command: sh -c "yarn install && node index.js"
    ports:
      - '3000:3000'
